version: '3'

services:
  auth-service:
    build:
      context: .
      dockerfile: ./services/auth_service/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REDIRECT_URI=http://localhost:8001/auth/callback
      - REDIS_HOST=redis
    depends_on:
      - redis

  email-service:
    build:
      context: .
      dockerfile: ./services/email_service/Dockerfile
    ports:
      - "8002:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
      - REDIS_HOST=redis
    depends_on:
      - auth-service
      - redis
      - rabbitmq

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"